//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : aru_1.java
//  @ Date : 2020. 12. 02.
//  @ Author : 
//
//




public class aru_1 {
	private int aru_id;
	private String aru_nev;
	private int aru_ar;
	private String aru_leiras;
	private int aru_ertekeles;
	private Date aru_keszites_datuma;
	public void get_aru_nev() {
	}
	
	public void get_aru_nev() {
	}
	
	public void get_aru_leiras() {
	}
	
	public void get_aru_ertekeles() {
	}
	
	public void aru_ar_elteres(Object int ar1, Object int ar2) {
	}
}
