//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : aruk.java
//  @ Date : 2020. 12. 02.
//  @ Author : 
//
//




public class aruk {
	private int aru_id;
	private String aru_nev;
	private int aru_ar;
	private String aru_leiras;
	private int aru_ertekeles;
	private Date aru_keszites_datuma;
	public void get_aru_nev() {
	}
	
	public void get_aru_ar() {
	}
	
	public void get_aru_leiras() {
	}
	
	public void get_aru_ertekeles() {
	}
	
	private void get_aru_id() {
	}
}
